version: "3.4"

networks:
   frontend:
   backend:
   
services:
   JWTLogin:
      build:
         context: .
         dockerfile: JWTLogin/Dockerfile
      image: jwtlogint
      environment:
         - DatabaseServer=mssqlserver
         - DatabaseName=User
         - DatabaseUser=sa
         - DatabasePassword=Password123
         - ExternalCatalogBaseUrl=http://${RPGSHOP_EXTERNAL_DNS_NAME_OR_IP}:7000
      container_name: jwt
      ports:
         - "7000:80"
      networks:
         - backend
         - frontend

   mssqlserver:
      image: "mcr.microsoft.com/mssql/server"
      ports:
         - "1445:1433"
      container_name: jwtcogincontainer
      environment:
         - ACCEPT_EULA=Y
         - SA_PASSWORD=Password123
      networks:
         - backend